Feat/parse packet unit test
oresat/oresat-c3-software pull request #2
Opened 2023-04-23 02:24 UTC by Tlabting

Added additional unit tests for edl.py
I also included a filterwarning to ignore a deprecation warning on generating a bad packet, which is used in a unit test to trigger an invalid FECF exception.

2023-04-25 16:08 UTC, ryanpdx requested changes
Looks great!

Just some minor changes and one question

2023-04-25 16:08 UTC, ryanpdx commented on tests/test_edl.py
> +from spacepackets.uslp.frame import TransferFrame, FrameType
The `unittest` module is already imported, no reason to import `patch` directly

2023-04-25 20:35 UTC, dmitri-mcguckin commented on tests/test_edl.py
> +from spacepackets.uslp.frame import TransferFrame, FrameType
While I agree imports should occur at the top, importing directly or aliasing via the `as` keyword is useful if you don't want to have to type `unittest.mock.patch.patch(...)` every time. Though if the reference is too vague and you'd like to know in the call which module `patch()` refers to. Maybe `import unittest.mock as um` is a good compromise?

Just food for thought.

2023-04-30 22:53 UTC, Tlabting commented on pyproject.toml
> +]
Yes, I was aware. I was getting a warning for a bad packet in the unit test where I purposefully create a bad packet. I was under the impression that the code I wrote was disabling the warning generated by pytest for the bad packet in response to the one created for the purpose of testing. Please correct me if I'm mistaken, I appreciate it!

2023-05-01 04:02 UTC, Tlabting commented on tests/test_edl.py
> +       with patch("oresat_c3.protocols.edl.crc16_bytes") as mock_crc16_bytes:
The reason I decided to use patch here is to mock out the return value for the crc16_bytes function call in edl.py on line 269 in order to test for the UslpInvalidRawPacketOrFrameLen Exception. If I did not mock this, the Exception on line 271 was caught instead. If there is a better way to do it, please let me know. I am always eager to learn new techniques!

2023-05-29 17:06 UTC, ryanpdx approved these changes

2023-05-29 17:06 UTC, merged